### ISSUE TITLE
water year vs calendar year.

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRETci#14]
```
I am using the EGRETci package to evaluate water quality trends for data in the Mississippi, Minnesota, and St. Croix Rivers. We investigate trends on a calendar year basis.  I was just looking for some clarification to make sure I am understanding the bootstrap results correctly.

Because I am investigating trends on a calendar year basis, I made sure for my eList that paStart=1 and paLong=12.  For this site the first water quality sample was 2/8/1985 and the last sample was 12/19/2014. I then wanted to see the trend for calendar year 2005 to calendar year 2014 (last 10 years).  Here are the first few lines of my bootstrap output text file:

Minnesota River at Jordan  Chloride

Calendar Year

  Bootstrap process, for change from Water Year 2005 to Water Year 2014
                   data set runs from WaterYear 1985 to Water Year 2015
  Bootstrap block length in days 200
  bootBreak is 39  confStop is 0.7


I am confused by how the program summarizes data by water year.  The program knows I want to evaluate by calendar year, but the summary still says I am looking at water year 2005 to 2014. It then says I have samples from water year 1985 to water year 2015, because I had samples after 10/1/2014.  So does the output mean I am looking at change from calendar year 2005 to 2014 but says “water year” anyways? Or did it change my request to look at water year 2005 to water year 2014 after all?  I just want to make sure my 2014 October –December samples are being used and from this summary I’m not sure they are.
```

```
I took a look at this question and I think I know what is going on.  My question to you is ask you to run look at your original WRTDS results for calendar year for the period of interest to you.  

That means you want to do this:

eList <- setPA(paStart=1, paLong=12)
tableChange(eList, yearPoints=c(2005,2014))

from that output take note of the change values for concentration in mg/L and for flux in 10^6 kg/yr.

Now use EGRETci and do this:

caseSetUp <- trendSetUp(eList)

then it will ask you for first water year, tell it 2005,  then last water year, tell it 2014.  

then it will ask for nBoot, bootBreak and blockLength,  You can give it 5 and 5 and 200.  (It won't really matter here, I just want you to be able to get the result quickly - when you really run it you will want bigger values for the first two of these).

Then. 

eBoot <- wBT(eList,caseSetUp)

when you look at the results, near the top you will have two lines that say something like this:  

WRTDS estimated concentration change is xxx  mg/L
 WRTDS estimated flux change is          yyy  10^6 kg/yr

The xxx should match the concentration change and the yyy the flux change you got in tableChange.  

I tried it with an example of my own and it worked fine.  Assuming the numbers work out for you then the interpretation is this.  This is really a trend test on change from calendar year 2005 to calendar year 2014.

The upshot is that we need to change what our automatic output says, but the computations are doing exactly what you want.  When we started designing the software we made it work just for Water Year.  Then we changed to making it more flexible, but we never went back and changed the message that prints out.

Let us know if this experiment works.

Laura: can you look at a way of changing the code to reflect what is really being tested?  We also needs to see that it works for any arbitrary choice of paStart and paLong so it might not even be a whole year.  The paLong and paStart in eList$INFO are driving the test, but the stuff we print doesn't really reflect that.  Probably need to say what the PA actually is and defines the starting and ending  of the period being evaluated.
```

**Comment by msimoneau-mddelcc** [comment]
Hi Laura,
 I just found out yesterday about the water year vs calendar year issue.
I have been using calendar years for a long time in my analyses. I was kind of puzzled to see that the output was always showing water years instead of calendar years even though I made sure my eList statement was OK , that is :
 eList <- setPA(eList,paStart=1,paLong=12).
I ran the test you suggested and was pleased to see that the results in the EGRETci output were exactly the same as the ones shown in tableChange.
I have a question though. My data run from 1/14/1979 to 12/15/2015.
If I use 1979 as my starting year and 2015 as my ending year in the caseSetUp<-trendSetUp(eList), I am getting this error message:
Error in wBT(eList, caseSetUp, fileName = "ETCH_BootstrapResults.txt") : 
  Error in resultSurvReg[k, ]: subscript out of bounds
/nNANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANAN

Everything works fine if I use 1980 as my starting year instead of 1979. Do you have an explanation for this?

**Comment by ldecicco-USGS** [comment]
Are you able to install like this:

```r
library(devtools)
install_github("USGS-R/EGRETci")
```

If so, let me know if this version works for you. I think it's an indexing issue, it's looking for a place to add some information to the `surface` but it's a little bit before your data starts in the calendar year.

**Comment by msimoneau-mddelcc** [comment]
Hi Laura,

Thank you very much for the quick reply.
I followed your advice and used :


library(devtools)

install_github("USGS-R/EGRETci")



… and I got this message:

Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
  Couldn't connect to server

I did download the latest version of EGRETci  which is 1.0.2 and I am still getting the same error message.

Error in wBT(eList, caseSetUp, fileName = "ETCH_BootstrapResults.txt") :
  Error in resultSurvReg[k, ]: subscript out of bounds
/nNANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANANAN


I am using R-3.2 for Windows. Should I update to the latest version?

Thank you again for your help.
I hope this is not a simple code-18 error, that is the error is located 18 inches in front of the screen.
☺


Marc Simoneau
Water Quality Analyst

Ministère du Développement durable, de l'Environnement et  de la Lutte contre les Changements climatiques (MDDELCC)
Direction générale du suivi de l'état de l'environnement (DGSEE)
Direction de l'information sur les milieux aquatiques (DIMAQ)
Édifice Marie-Guyart, 7e étage, boîte 22
675 boulevard René-Lévesque Est,
Québec (Québec) G1R 5V7 CANADA

Téléphone: (418) 521-3820, poste 4707
Télécopieur: (418) 643-9591
Courriel : marc.simoneau@mddelcc.gouv.qc.ca<mailto:marc.simoneau@mddelcc.gouv.qc.ca>
Internet : www.mddelcc.gouv.qc.ca<http://www.mddelcc.gouv.qc.ca/>
Internet : Atlas interactif de la qualité des eaux de surface et des écosystèmes aquatiques<http://www.mddelcc.gouv.qc.ca/eau/Atlas_interactif/donnees_recentes/donnees_iqbp6.asp>

Avis de confidentialité: Le présent message et ses annexes sont confidentiels. Ils ne peuvent être utilisés par leur destinataire que pour les fins convenues. Si ce message et ses annexes vous ont été transmis par erreur, veuillez les détruire et nous en aviser aussitôt. Merci.



De : Laura DeCicco [mailto:notifications@github.com]
Envoyé : Tuesday, November 01, 2016 6:14 PM
À : USGS-R/EGRETci <EGRETci@noreply.github.com>
Cc : Simoneau, Marc <Marc.Simoneau@mddelcc.gouv.qc.ca>; Comment <comment@noreply.github.com>
Objet : Re: [USGS-R/EGRETci] water year vs calendar year. (#14)


Are you able to install like this:

library(devtools)

install_github("USGS-R/EGRETci")

If so, let me know if this version works for you. I think it's an indexing issue, it's looking for a place to add some information to the surface but it's a little bit before your data starts in the calendar year.
