### ISSUE TITLE
Add set.seed argument for reproducibility

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRETci#22]

**Comment by ldecicco-USGS** [comment]
@lindsaycarr you could probably take on this issue. The only randomization that happens in this package is `sample` in the `bootSample` function. Somehow though, we need to be able to easily specify the seed so that the whole workflow is completely repeatable. 

So, I would make an argument in `trendSetUp` that saves the seed. Then...make sure the other functions use that seed.

I'm hazy on some details here, so I'm hoping you'll do a bit of investigating to make sure that it's completely reproducible.

**Comment by lindsaycarr** [comment]
@ldecicco-USGS where is the `bootSample` function? I don't see that anywhere

**Comment by ldecicco-USGS** [comment]
Sorry...`blockSample` :

https://github.com/USGS-R/EGRETci/blob/master/R/wBTCode.R#L790

**Comment by lindsaycarr** [comment]
@ldecicco-USGS this has been floating around on my calendar but I stopped pursuing it because you said something about waiting until you finished something else. Just let me know if I should resume work on this.
