### ISSUE TITLE
BlankTime() and cibands

### ISSUE THREAD

**Issue by emorway-usgs** [USGS-R/EGRETci#5]
After a call to blankTime to filter a time span with missing data, it would seem that a call to ciBands (after running the required commands prior to calling ciBands) doesn't work?  The error message is shown below, it is one I haven't seen before and I think it may be related to the fact that I've applied blankTime higher up in the script:

```
...
CIAnnualResults <- ciBands(eList, repAnnual, probs)
#Error in quantile.default(manyAnnualResults[iYear, 1, 1:nBoot], prob = probs,  : 
#  missing values and NaN's not allowed if 'na.rm' is FALSE
```

**Comment by ldecicco-USGS** [comment]
Try using the latest development version, and let me know if the problem is fixed. To install:

```
devtools::install_github("USGS-R/EGRETci")

```

**Comment by emorway-usgs** [comment]
Results look good post-fix:
![cibands_blanktime](https://cloud.githubusercontent.com/assets/3236576/14569309/cbd3a70e-02f2-11e6-93fd-026aece66be6.png)
