### ISSUE TITLE
wBT and ciCalculations take a REALLY long time

### ISSUE THREAD

**Issue by nkday** [USGS-R/EGRETci#54]
It takes about 10 minutes for wBT to run and I haven't successfully gotten ciCalculations to run. Any ideas?

**Comment by ldecicco-USGS** [comment]
Can you send me an eList?

ciCalculations do take a *really* long time. The code in the parallel vignette can speed it up a bit:

http://usgs-r.github.io/EGRETci/articles/EGRETci.html#parallel-computing
