### ISSUE TITLE
Only one dashed line for CIs

### ISSUE THREAD

**Issue by StefanoMezzini** [USGS-R/EGRETci#55]
There is only one dashed line for the 95% CIs in my plots from `plotConcHistBoot()`. Some times it looks like an upper 95% CI, other times I have no idea:
![image](https://user-images.githubusercontent.com/42444204/50714909-51edc880-1040-11e9-96b6-a60c732b5fb2.png)
![image](https://user-images.githubusercontent.com/42444204/50714930-6df16a00-1040-11e9-95f4-7e542f1ec7d6.png)

**Comment by msimoneau-mddelcc** [comment]
I'm having the same problem. The reason why this is happening seems to be related to the CIAnnualResults function which produces the sames results for both the FNConcLow and FNConcHigh and also the FNFluxLow and FNFluxHigh.
I'm using the EGRET 3.0.2 and EGRETci 2.0.3

**Comment by msimoneau-mddelcc** [comment]
versions.

 CIAnnualResultsPTOT
       Year  FNConcLow FNConcHigh FNFluxLow FNFluxHigh
1  1999.499 0.05528543 0.05528543 110.18171  110.18171
2  2000.499 0.05358655 0.05358655 107.06823  107.06823
3  2001.499 0.05186005 0.05186005 102.78940  102.78940
4  2002.499 0.05028994 0.05028994  99.38829   99.38829
5  2003.499 0.04880477 0.04880477  96.17194   96.17194
6  2004.499 0.04746067 0.04746067  93.75135   93.75135
7  2005.499 0.04609238 0.04609238  90.30500   90.30500
8  2006.499 0.04483760 0.04483760  87.57953   87.57953
9  2007.499 0.04361833 0.04361833  84.90942   84.90942
10 2008.499 0.04242828 0.04242828  82.51471   82.51471
11 2009.499 0.04171198 0.04171198  80.06793   80.06793
12 2010.499 0.04122319 0.04122319  78.62628   78.62628
13 2011.499 0.04086851 0.04086851  77.28958   77.28958
14 2012.499 0.04065544 0.04065544  76.56875   76.56875
15 2013.499 0.04046181 0.04046181  75.06925   75.06925
16 2014.499 0.04036688 0.04036688  74.16470   74.16470
17 2015.499 0.04032379 0.04032379  73.36662   73.36662
18 2016.499 0.04034939 0.04034939  73.07293   73.07293
19 2017.499 0.04034219 0.04034219  71.96389   71.96389

![image](https://user-images.githubusercontent.com/11968599/59932070-666a2580-9414-11e9-8814-595c4fde5f3a.png)

**Comment by ldecicco-USGS** [comment]
Ack, sorry I missed this issue earlier! I'll try to have a look today. Just a warning though I'll be on vacation next week, so if I can't figure it out today, it'll be a week.

**Comment by camason01** [comment]
Was the cause of this issue targeted?

**Comment by StefanoMezzini** [comment]
After updating all packages with `checkBuilt = TRUE` (R version 4.0.5), I still have the same problem. I haven't used EGRET and EGRETci in a few years though.

```plotConcHistBoot(eList = x, CIAnnualResults = y, printTitle = FALSE)```
![image](https://user-images.githubusercontent.com/42444204/116893982-ca53fc80-abee-11eb-9636-ff53055544ff.png)

**Comment by camason01** [comment]
I have the same results. It seems the lower band is repeated and something is going wrong in the ciBands function.
> quantConc
       5%       95% 
0.6749886 0.6749886 

Yet,
> probs
[1] 0.05 0.95

**Comment by ldecicco-USGS** [comment]
If someone could send me their "eList" or script to create the eList, that would be fantastic! I haven't been able to recreate it, but I'd be happy to take a look. (I don't know how great github does with attachments, so send it via email to ldecicco@usgs.gov)

**Comment by StefanoMezzini** [comment]
I'm currently working on a reproducible example

**Comment by camason01** [comment]
I also just emailed along an eList.

**Comment by StefanoMezzini** [comment]
I now get two bands, the single-band issue only occurs when I use old objects I created a few years ago. For stability purposes, however, it is best to run at least 10,000 simulations when calculating the CIs.

**Comment by camason01** [comment]
I'm posting a follow-up in case someone stumbles across this thread with the same issue I've experience. A colleague of mine pointed out yesterday that the set.seed defaults differ between the bootAnnual and ciBands functions. The former's default is repeated and the latter's is random. This was my issue since if all your predicted values stem from the same repeated random sequence, the confidence probabilities will also be the same, regardless of your selected intervals. Thanks to all for chiming in to help even though this thread was nearly two years old.

**Comment by ldecicco-USGS** [comment]
Yup, thanks for figuring that out! There was an update to EGRETci a few years back that caused that issue (we had to change it so people could reproduce the CIs). But it did require scripts to be changing the `bootAnnual` function to have the "startSeed " argument :
```
nCores <- detectCores() - coreOut
cl <- makeCluster(nCores)
registerDoParallel(cl)
repAnnual <- foreach(n = 1:nBoot,.packages=c('EGRETci')) %dopar% {
   annualResults <- bootAnnual(eList, 
                               blockLength,
                               startSeed = n)  
}
stopCluster(cl) 
```
Sorry for the confusion!
