### ISSUE TITLE
Please verify xFlux computation

### ISSUE THREAD

**Issue by thodson-usgs** [USGS-R/EGRETci#58]
The doc for runPairsBoot.R states:
"xConc, xFlux are vectors of length iboot, of the change in flow normalized concentration of flux computed by each bootstrap replicate (mg/L)"

and xConc, xFlux are computed on line 161-162 of runPairsBoot.R  as:
xConc_here <- (2 * regDeltaConc) - (c22 - c11)
xFlux_here <- (2 * regDeltaFlux) - (f22 - f11)

Where regDeltaConc is the change in flow normalized flux computed by runPairs.R:
 (c22 - c11)

My question is,  if both xConc and regDeltaConc represent the change in flow normalized concentration, why is one: (2 * regDeltaConc) - (c22 - c11)
and the other: (c22 - c11).

Should they both be c22-c11 (and the same for flux)?

**Comment by ldecicco-USGS** [comment]
Let's see...(I'm just talking myself through this):
(2 * regDeltaConc) - (c22 - c11) *would* be the equivalent of (c22 - c11)...if regDeltaConc was simply (c22 - c11) [2x - 1x == x]
But:
`regDeltaConc` comes from `runPairs` using the whole dataset. 
`c22` and `c11` in the `runPairsBoot` function are using a bootstrapped sample. 

So, is your question why the individual bootstrap calculations don't use the simple c22_boot - c11_boot, right? I'll try to go back to my notes or see if Bob knows off-hand.

By the way, I think I just passed on your name to someone looking for a Python dataRetrieval. How complete is that package?

**Comment by thodson-usgs** [comment]
Thanks for follow up. 
That's correct.
I noticed this issue after tweaking the code to output uncertainty for the GFN components. My results weren't matching up with the original b/c I intuitively used (f22-f11) instead of (2 * regDeltaFlux) - (f22-f11).

The NWIS/STORET portion of python dataretrieval is stable, but this reminds me that I should refresh the version that's up on pip.

**Comment by thodson-usgs** [comment]
The code is correct. Closing this issue.
See discussion of empirical vs percentile bootstrap at
https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/readings/MIT18_05S14_Reading24.pdf

**Comment by ldecicco-USGS** [comment]
Thanks for the reference! Bob was pretty sure it was correct when I talked to him, but wanted to find a reference like that to use to help explain it.
