### ISSUE TITLE
error in wBT runs- results must align with PA?

### ISSUE THREAD

**Issue by jbreng-srbc** [USGS-R/EGRETci#66]
Hello,  

Getting this reproducible error while running wBT and runPairs: 
`Error in if (z) "Reject Ho" else "Do Not Reject Ho" : 
  missing value where TRUE/FALSE needed`

Attached are example input text files used in model runs that produce error and my code as R script.

When using either input text file "as is", I get the error and change calculations are significantly off (Flux Change is actually NA): 

**"Susquehanna River at Danville, PA  Nitrate-Nitrite**

**Water Year**

  **Bootstrap process, for change from Water Year1986 to Water Year2019
                   data set runs from 1986 to Year 2019
  Bootstrap block length in days 200
  bootBreak is 3  confStop is 0.7**

 **WRTDS estimated concentration change is   _25256  mg/L_
 WRTDS estimated flux change is               _NA  10^6 kg/yr_"**

When I inputted "fake" results that complete the 1986 water year (in my case, I actually added fake sample results just for September or October), I no longer get the error.

Reproduced this same error for other input files and other sites.

Must the input sample result dates exactly coincide with the period of analysis (PA) in order for wBT to run without this error?    

Thank you!

[01540500_trend_git.zip](https://github.com/USGS-R/EGRETci/files/5029149/01540500_trend_git.zip)
[01540500dn - Original.txt](https://github.com/USGS-R/EGRETci/files/5029065/01540500dn.-.Original.txt)
[01540500dn.txt](https://github.com/USGS-R/EGRETci/files/5029067/01540500dn.txt)

**Comment by ldecicco-USGS** [comment]
Thanks for bringing this up! I've had similar experiences, and basically ignored the problem or just bumped my starting year up...but you made me realize this is actually a fixable bug. I think the fix was needed in EGRET in the setupYears function, so if you install:

```r
remotes::install_github("USGS-R/EGRET")
```
I think you can now get water year 1985. Let me know if that doesn't fix it for you.

**Comment by jbreng-srbc** [comment]
Thank you for your timely response Laura, really appreciate it (as well as all your fantastic work on WRTDS packages!).  I’ll give your suggestion a try.

This may not be a bug but a sensible restriction, given it makes sense to have complete data lining up with Year1 of trend run.

Ultimately, the question I’m hoping to get answered is:  what’s best way for users like myself, to include data that doesn’t necessarily begin in Year1 of trend run, but does span majority of months in PA?  I’d prefer to include those data somehow, rather than trash them.  My assumption is bumping back starting year excludes data?

Thank you again,

- Josh

**Comment by ldecicco-USGS** [comment]
There's still a check to make sure the year has enough data points. If there's NA's for more than 10% of the year, the annual results will come back with NA, and the year comparisons can't be calculated.

The entire WRTDS "surface" is still used when calculating the trends, so if you want to use the earliest possible year, as long as there's enough data, the trends can be calculated. I usually add a buffer year if the project allows it (like, assuming there's nothing special about absolute year 1).

**Comment by jbreng-srbc** [comment]
Thank you for insights Laura, very much appreciate them.  Helpful to know the “10% rule”, that the entire WRTDS surface is still used, and your personal work around.  My datasets are long enough that buffer year is no problem.

I realize this is not the ideal forum to ask this question, but is there a centralized WRTDS user group where I can gain access to other scientist’s WRTDS based analysis/research, training opportunities, ask questions, etc.?

Best,

- Josh

**Comment by ldecicco-USGS** [comment]
Well, we use to have an email list, but the USGS moved from a Google platform to a Microsoft one, and I'm not 100% sure it still works. That being said, it was only for announcements, not general discussion. I prefer people creating issues here or on the main EGRET github page. That way, if I answer a question, it's always accessible (if someone browses or searches closed issues). And if I realize it's the same question, I can point them to the archived answer. Occasionally, other users chime in too.

**Comment by jbreng-srbc** [comment]
Ok, thank you Laura for that information and again, for all the insights regarding my data that didn’t span an entire water year.

**Comment by ldecicco-USGS** [comment]
We recently updated a few things in "setupYears" and the plotConcHist functions. I think the issues raised here are fixed, but feel free to re-open if something like this continues to happen. (currently only on github versions:
```r
remotes::install_github("USGS-R/EGRET")
```
