### ISSUE TITLE
Error-plotHistogramTrend for Flux

### ISSUE THREAD

**Issue by Farshad171** [USGS-R/EGRETci#7]
Error in hist.default(reps, breaks = xSeq, yaxs = "i", xaxs = "i", tcl = 0.5,  : 
  some 'x' not counted; maybe 'breaks' do not span range of 'x

Here is the list:
rep              Concentration             |              Flux
          value     nPos post_p   Lower   Upper  |     value   nPos  post_p    Lower   Upper
       1 -0.0309     0 0.25 -0.0309 -0.0309   |      0.283     1    0.75    0.283    0.283
       2 -0.0168     0 0.167 -0.0309 -0.0168   |     0.6621     2   0.833    0.283   0.6621
       3   -0.03     0 0.125 -0.0309 -0.0168   |     0.3014     3   0.875    0.283   0.6621
       4 -0.0181     0 0.1 -0.0309 -0.0168   |     0.7496     4     0.9    0.283   0.7496
       5 -0.0169     0 0.0833 -0.0309 -0.0168   |     0.5048     5   0.917    0.283   0.7496
       6 -0.0101     0 0.0714 -0.0309 -0.0101   |     0.7315     6   0.929    0.283   0.7496
       7 -0.0636     0 0.0625 -0.0636 -0.0101   |    -0.4792     6   0.812  -0.4792   0.7496
       8 -0.0528     0 0.0556 -0.0636 -0.0101   |    -0.6414     6   0.722  -0.6414   0.7496
       9 -0.0171     0 0.05 -0.0636 -0.0101   |     0.6196     7    0.75  -0.6414   0.7496
      10 -0.0307     0 0.0455 -0.0636 -0.0101   |     0.5275     8   0.773  -0.6414   0.7496
      11  -0.013     0 0.0417 -0.0636 -0.0101   |     0.8981     9   0.792  -0.6414   0.8981
      12  -0.017     0 0.0385 -0.0636 -0.0101   |     0.7489    10   0.808  -0.6414   0.8981
      13 -0.0452     0 0.0357 -0.0636 -0.0101   |     0.4748    11   0.821  -0.6414   0.8981
      14 -0.0345     0 0.0333 -0.0636 -0.0101   |     0.2384    12   0.833  -0.6414   0.8981
      15 -0.0337     0 0.0312 -0.0636 -0.0101   |     0.2557    13   0.844  -0.6414   0.8981
      16 -0.0265     0 0.0294 -0.0636 -0.0101   |     0.3773    14   0.853  -0.6414   0.8981
      17 -0.0541     0 0.0278 -0.0636 -0.0101   |    -0.3951    14   0.806  -0.6414   0.8981
      18 -0.0287     0 0.0263 -0.0636 -0.0101   |     0.6072    15   0.816  -0.6414   0.8981
      19 -0.0486     0 0.025 -0.0636 -0.0101   |    -0.5431    15   0.775  -0.6414   0.8981
      20 -0.0262     0 0.0238 -0.0632 -0.0103   |     0.4925    16   0.786  -0.6364   0.8907
      21 -0.0859     0 0.0227 -0.0836 -0.0104   |    -0.7203    16    0.75  -0.7124   0.8833
      22 -0.0391     0 0.0217 -0.0825 -0.0105   |    -0.0548    16   0.717  -0.7085   0.8759
      23 -0.00791     0 0.0208 -0.0814 -0.00835   |     0.9121    17   0.729  -0.7045   0.9093
      24  -0.042     0 0.02 -0.0803 -0.00846   |      0.878    18    0.74  -0.7006   0.9086
      25  -0.047     0 0.0192 -0.0792 -0.00857   |   -0.02709    18   0.712  -0.6966   0.9079
      26 -0.0191     0 0.0185 -0.0781 -0.00868   |     0.5373    19   0.722  -0.6927   0.9072
      27 -0.0403     0 0.0179  -0.077 -0.00879   |     0.4758    20   0.732  -0.6887   0.9065
      28 -0.0671     0 0.0172 -0.0774 -0.0089   |     0.0856    21   0.741  -0.6848   0.9058
      29  -0.021     0 0.0167 -0.0765 -0.00901   |     0.2997    22    0.75  -0.6808   0.9051
      30 -0.0259     0 0.0161 -0.0756 -0.00912   |   0.007642    23   0.758  -0.6769   0.9044
      31 -0.00347     0 0.0156 -0.0746 -0.00613   |     0.6906    24   0.766  -0.6729   0.9037
      32 -0.0465     0 0.0152 -0.0737 -0.00635   |    -0.6041    24   0.742   -0.669    0.903
      33 -0.0117     0 0.0147 -0.0727 -0.00658   |    0.06099    25    0.75   -0.665   0.9023
      34 -0.0362     0 0.0143 -0.0718 -0.0068   |     0.8749    26   0.757  -0.6611   0.9016
      35 -0.00482     0 0.0139 -0.0709 -0.00455   |     0.4456    27   0.764  -0.6571   0.9009
      36 -0.0547     0 0.0135 -0.0699 -0.00462   |    -0.8404    27   0.743  -0.7383   0.9002
      37 -0.0518     0 0.0132  -0.069 -0.00469   |    -0.2126    27   0.724  -0.7323   0.8995
      38 -0.0171     0 0.0128 -0.0681 -0.00476   |     0.3157    28   0.731  -0.7263   0.8988
      39 -0.0405     0 0.0125 -0.0671 -0.00482   |     0.3362    29   0.738  -0.7203   0.8981

**Comment by ldecicco-USGS** [comment]
Any chance you could send me the eList object (or a reproducible way to get the data)?

**Comment by ldecicco-USGS** [comment]
Try using the latest development version, and let me know if the problem is fixed. To install:

```
devtools::install_github("USGS-R/EGRETci")

```

**Comment by Farshad171** [comment]
I have not yet tried the new version, but I was able to fix it by
increasing the range. Apparently, the range of default values were not
enough wide to accommodate the Flux result. Thank you.

On Wed, Apr 13, 2016 at 3:06 PM, Laura DeCicco <notifications@github.com>
wrote:

> Try using the latest development version, and let me know if the problem
> is fixed. To install:
>
> devtools::install_github("USGS-R/EGRETci")
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/EGRETci/issues/7#issuecomment-209647323>
>



-- 
Best regards,

Farshad Shafiei

PhD candidate in Limnology
University of Saskatchewan
112 Science place Saskatoon
SK, S7N 5E2

Tel: 306-715-1660
Email: fsh.shafiei@Gmail. com
https://www.linkedin.com/profile/view?id=136086379&trk=nav_responsive_tab_profile
